### ISSUE TITLE
Can gcc 7.1.1 be used to compile gambit 16.0.1?

### ISSUE THREAD

**Issue by stefanhusmann** [gambitproject/gambit#220]
I have problems compiling gambit 16.0.1 from git under Arch Linux. I suspect gcc 7.1.1 as the culprit.

```
==> Erstelle Paket: gambit-git 16.0.1-1 (Do 29. Jun 16:05:48 CEST 2017)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> Aktualisiere das gambit git Repo...
Fordere an von origin
==> Überprüfe source Dateien mit md5sums...
    gambit ... Übersprungen
==> Entpacke Quellen...
  -> Erstelle Arbeitskopie des gambit git Repos...
Zu neuem Branch 'makepkg' gewechselt
==> Beginne pkgver()...
==> Entferne existierendes $pkgdir/ Verzeichnis...
==> Beginne build()...
aclocal: warning: couldn't open directory 'm4': No such file or directory
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:64: installing './config.guess'
configure.ac:64: installing './config.sub'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit/missing: Unknown `--is-lightweight' option
Try `/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1879296
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether we are building for a Win32 host... no
checking for bcmp... yes
checking for srand48... yes
checking for drand48... yes
checking for wx-config... /usr/bin/wx-config
checking for wxWidgets version >= 2.8.12... yes (version 3.0.3)
checking for wxWidgets static library... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/Makefile
config.status: creating contrib/scripts/Makefile
config.status: creating contrib/scripts/enumpoly/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
(CDPATH="${ZSH_VERSION+.}:" && cd . && autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-recursive
make[1]: Entering directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit'
Making all in contrib
make[2]: Entering directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit/contrib'
Making all in scripts
make[3]: Entering directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit/contrib/scripts'
Making all in enumpoly
make[4]: Entering directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit/contrib/scripts/enumpoly'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit/contrib/scripts/enumpoly'
make[4]: Entering directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit/contrib/scripts'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit/contrib/scripts'
make[3]: Leaving directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit/contrib/scripts'
make[3]: Entering directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit/contrib'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit/contrib'
make[2]: Leaving directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit/contrib'
make[2]: Entering directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit'
depbase=`echo library/src/integer.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I.  -I./src -I./library/include -I./src/labenski/include -I/usr/lib/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++11 -MT library/src/integer.o -MD -MP -MF $depbase.Tpo -c -o library/src/integer.o library/src/integer.cc &&\
mv -f $depbase.Tpo $depbase.Po
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h: In member function 'void Gambit::weak_ptr<T>::swap(const Gambit::weak_ptr<T>&)':
./library/include/gambit/shared_ptr.h:137:37: error: no matching function for call to 'swap(long int*&, long int* const&)'
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7.1.1/bits/nested_exception.h:40:0,
                 from /usr/include/c++/7.1.1/exception:143,
                 from /usr/include/c++/7.1.1/ios:39,
                 from /usr/include/c++/7.1.1/ostream:38,
                 from /usr/include/c++/7.1.1/iostream:39,
                 from library/src/integer.cc:37:
/usr/include/c++/7.1.1/bits/move.h:187:5: note: candidate: template<class _Tp> typename std::enable_if<std::__and_<std::__not_<std::__is_tuple_like<_Tp> >, std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> >::value>::type std::swap(_Tp&, _Tp&)
     swap(_Tp& __a, _Tp& __b)
     ^~~~
/usr/include/c++/7.1.1/bits/move.h:187:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   deduced conflicting types for parameter '_Tp' ('long int*' and 'long int* const')
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7.1.1/bits/nested_exception.h:40:0,
                 from /usr/include/c++/7.1.1/exception:143,
                 from /usr/include/c++/7.1.1/ios:39,
                 from /usr/include/c++/7.1.1/ostream:38,
                 from /usr/include/c++/7.1.1/iostream:39,
                 from library/src/integer.cc:37:
/usr/include/c++/7.1.1/bits/move.h:210:5: note: candidate: template<class _Tp, long unsigned int _Nm> typename std::enable_if<std::__is_swappable<_Tp>::value>::type std::swap(_Tp (&)[_Nm], _Tp (&)[_Nm])
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
     ^~~~
/usr/include/c++/7.1.1/bits/move.h:210:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types '_Tp [_Nm]' and 'long int*'
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7.1.1/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7.1.1/bits/char_traits.h:39,
                 from /usr/include/c++/7.1.1/ios:40,
                 from /usr/include/c++/7.1.1/ostream:38,
                 from /usr/include/c++/7.1.1/iostream:39,
                 from library/src/integer.cc:37:
/usr/include/c++/7.1.1/bits/stl_pair.h:490:5: note: candidate: template<class _T1, class _T2> void std::swap(std::pair<_T1, _T2>&, std::pair<_T1, _T2>&)
     swap(pair<_T1, _T2>& __x, pair<_T1, _T2>& __y)
     ^~~~
/usr/include/c++/7.1.1/bits/stl_pair.h:490:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types 'std::pair<_T1, _T2>' and 'long int*'
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7.1.1/string:52:0,
                 from /usr/include/c++/7.1.1/bits/locale_classes.h:40,
                 from /usr/include/c++/7.1.1/bits/ios_base.h:41,
                 from /usr/include/c++/7.1.1/ios:42,
                 from /usr/include/c++/7.1.1/ostream:38,
                 from /usr/include/c++/7.1.1/iostream:39,
                 from library/src/integer.cc:37:
/usr/include/c++/7.1.1/bits/basic_string.h:6044:5: note: candidate: template<class _CharT, class _Traits, class _Alloc> void std::swap(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&)
     swap(basic_string<_CharT, _Traits, _Alloc>& __lhs,
     ^~~~
/usr/include/c++/7.1.1/bits/basic_string.h:6044:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>' and 'long int*'
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7.1.1/tuple:39:0,
                 from /usr/include/c++/7.1.1/bits/unique_ptr.h:37,
                 from /usr/include/c++/7.1.1/bits/locale_conv.h:41,
                 from /usr/include/c++/7.1.1/locale:43,
                 from /usr/include/c++/7.1.1/iomanip:43,
                 from ./library/include/gambit/gambit.h:29,
                 from library/src/integer.cc:45:
/usr/include/c++/7.1.1/array:294:5: note: candidate: template<class _Tp, long unsigned int _Nm> void std::swap(std::array<_Tp, _Nm>&, std::array<_Tp, _Nm>&)
     swap(array<_Tp, _Nm>& __one, array<_Tp, _Nm>& __two)
     ^~~~
/usr/include/c++/7.1.1/array:294:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types 'std::array<_Tp, _Nm>' and 'long int*'
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7.1.1/bits/unique_ptr.h:37:0,
                 from /usr/include/c++/7.1.1/bits/locale_conv.h:41,
                 from /usr/include/c++/7.1.1/locale:43,
                 from /usr/include/c++/7.1.1/iomanip:43,
                 from ./library/include/gambit/gambit.h:29,
                 from library/src/integer.cc:45:
/usr/include/c++/7.1.1/tuple:1602:5: note: candidate: template<class ... _Elements> void std::swap(std::tuple<_Tps ...>&, std::tuple<_Tps ...>&)
     swap(tuple<_Elements...>& __x, tuple<_Elements...>& __y)
     ^~~~
/usr/include/c++/7.1.1/tuple:1602:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types 'std::tuple<_Tps ...>' and 'long int*'
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7.1.1/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7.1.1/locale:43,
                 from /usr/include/c++/7.1.1/iomanip:43,
                 from ./library/include/gambit/gambit.h:29,
                 from library/src/integer.cc:45:
/usr/include/c++/7.1.1/bits/unique_ptr.h:669:5: note: candidate: template<class _Tp, class _Dp> void std::swap(std::unique_ptr<_Tp, _Dp>&, std::unique_ptr<_Tp, _Dp>&)
     swap(unique_ptr<_Tp, _Dp>& __x,
     ^~~~
/usr/include/c++/7.1.1/bits/unique_ptr.h:669:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types 'std::unique_ptr<_Tp, _Dp>' and 'long int*'
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7.1.1/functional:58:0,
                 from ./library/include/gambit/shared_ptr.h:27,
                 from ./library/include/gambit/gambit.h:120,
                 from library/src/integer.cc:45:
/usr/include/c++/7.1.1/bits/std_function.h:803:5: note: candidate: template<class _Res, class ... _Args> void std::swap(std::function<_Res(_ArgTypes ...)>&, std::function<_Res(_ArgTypes ...)>&)
     swap(function<_Res(_Args...)>& __x, function<_Res(_Args...)>& __y) noexcept
     ^~~~
/usr/include/c++/7.1.1/bits/std_function.h:803:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types 'std::function<_Res(_ArgTypes ...)>' and 'long int*'
     std::swap(m_count, other.m_count);
                                     ^
In file included from ./library/include/gambit/gambit.h:28:0,
                 from library/src/integer.cc:45:
/usr/include/c++/7.1.1/sstream:804:5: note: candidate: template<class _CharT, class _Traits, class _Allocator> void std::__cxx11::swap(std::__cxx11::basic_stringstream<_CharT, _Traits, _Allocator>&, std::__cxx11::basic_stringstream<_CharT, _Traits, _Allocator>&)
     swap(basic_stringstream<_CharT, _Traits, _Allocator>& __x,
     ^~~~
/usr/include/c++/7.1.1/sstream:804:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types 'std::__cxx11::basic_stringstream<_CharT, _Traits, _Allocator>' and 'long int*'
     std::swap(m_count, other.m_count);
                                     ^
In file included from ./library/include/gambit/gambit.h:28:0,
                 from library/src/integer.cc:45:
/usr/include/c++/7.1.1/sstream:797:5: note: candidate: template<class _CharT, class _Traits, class _Allocator> void std::__cxx11::swap(std::__cxx11::basic_ostringstream<_CharT, _Traits, _Allocator>&, std::__cxx11::basic_ostringstream<_CharT, _Traits, _Allocator>&)
     swap(basic_ostringstream<_CharT, _Traits, _Allocator>& __x,
     ^~~~
/usr/include/c++/7.1.1/sstream:797:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types 'std::__cxx11::basic_ostringstream<_CharT, _Traits, _Allocator>' and 'long int*'
     std::swap(m_count, other.m_count);
                                     ^
In file included from ./library/include/gambit/gambit.h:28:0,
                 from library/src/integer.cc:45:
/usr/include/c++/7.1.1/sstream:790:5: note: candidate: template<class _CharT, class _Traits, class _Allocator> void std::__cxx11::swap(std::__cxx11::basic_istringstream<_CharT, _Traits, _Allocator>&, std::__cxx11::basic_istringstream<_CharT, _Traits, _Allocator>&)
     swap(basic_istringstream<_CharT, _Traits, _Allocator>& __x,
     ^~~~
/usr/include/c++/7.1.1/sstream:790:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types 'std::__cxx11::basic_istringstream<_CharT, _Traits, _Allocator>' and 'long int*'
     std::swap(m_count, other.m_count);
                                     ^
In file included from ./library/include/gambit/gambit.h:28:0,
                 from library/src/integer.cc:45:
/usr/include/c++/7.1.1/sstream:783:5: note: candidate: template<class _CharT, class _Traits, class _Allocator> void std::__cxx11::swap(std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>&)
     swap(basic_stringbuf<_CharT, _Traits, _Allocator>& __x,
     ^~~~
/usr/include/c++/7.1.1/sstream:783:5: note:   template argument deduction/substitution failed:
In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h:137:37: note:   mismatched types 'std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>' and 'long int*'
     std::swap(m_count, other.m_count);
                                     ^
In file included from ./library/include/gambit/gambit.h:130:0,
                 from library/src/integer.cc:45:
./library/include/gambit/game.h: At global scope:
./library/include/gambit/game.h:843:31: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 Game ReadGame(std::istream &) throw (InvalidFileException);
                               ^~~~~
make[2]: *** [Makefile:2256: library/src/integer.o] Error 1
make[2]: Leaving directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit'
make[1]: *** [Makefile:2361: all-recursive] Error 1
make[1]: Leaving directory '/home/haawda/paketierung/meine_Pakete/gambit-git/src/gambit'
make: *** [Makefile:1367: all] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...

Process makepkg<1> exited abnormally with code 2
```

**Comment by stefanhusmann** [comment]
The same happens with stable release 15.1.1.

**Comment by tturocy** [comment]
The short and snarky answer is "obviously not." :)

I don't seem to have 7.1.x available on any system I currently have access to.  Are older/other versions available on Arch, to see whether it is the compiler version implicated or something else about the system?  I'm quite willing to bet it's the compiler version, and that indeed it's some evolution in C++ strictness that needs to be patched in the Gambit source.

**Comment by stefanhusmann** [comment]
I have a PKGBUILD for gcc63 in AUR, which builds and installs the
relesae 6.3.1, and using that is my current workaround. But that puts a
burden on the users of gambit to compile gcc63, which can take hours.

Both gambit versons (stable and deleopment) build fine with gcc 6.3.1.

**Comment by tturocy** [comment]
Many thanks.  Of course it is necessary to correct this - I do not mean to require gcc 6.3.x.  This is useful information to ascertain exactly what the issue is.

**Comment by tturocy** [comment]
I have had a look.  This appears to be a simple const-correctness problem.  In fact, it is somewhat mystifying that no other compiler complains about this, because the code is definitely not legal as written, never has been!  

I have pushed commit b911156 to branch maint15 which should correct this.  Could you confirm and/or report any other problems you find with gcc 7.1.x?

**Comment by jdemeyer** [comment]
> I have pushed commit b911156 to branch maint15 which should correct this. Could you confirm and/or report any other problems you find with gcc 7.1.x?

That works for me with GCC-7.2.0

**Comment by tturocy** [comment]
Many thanks @jdemeyer - that is very useful (and good) news.

**Comment by nsrosasco** [comment]
Hello!
I'm getting the following error:

In file included from ./library/include/gambit/gambit.h:120:0,
                 from library/src/integer.cc:45:
./library/include/gambit/shared_ptr.h: In member function ‘void Gambit::weak_ptr<T>::swap(const Gambit::weak_ptr<T>&)’:
./library/include/gambit/shared_ptr.h:137:37: error: no matching function for call to ‘swap(long int*&, long int* const&)’
     std::swap(m_count, other.m_count);
                                     ^
In file included from /usr/include/c++/7/bits/nested_exception.h:40:0,
                 from /usr/include/c++/7/exception:143,
                 from /usr/include/c++/7/ios:39,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from library/src/integer.cc:37:

From the 16.0.1 source (from http://www.gambit-project.org/), also with gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
I even tried manually adding in the line change from the patch mentioned in one of the threads, which generated more errors... Similar issues with 15, too.
Any help appreciated!
Thanks,
Nick Rosasco
