### ISSUE TITLE
fail to build with MacOS X 10.9

### ISSUE THREAD

**Issue by jdnull** [gambitproject/gambit#123]
I am trying to build with MacOS X 10.9, but getting such error massage: 
    "src/libgambit/integer.h:227:25: error: friend declaration specifying a default
      argument must be a definition"
    "src/libgambit/integer.h:228:19: error: friend declaration specifying a default
      argument must be a definition"
    "./src/libagg/trie_map.h:31:10: fatal error: 'ext/slist' file not found"
I find this is because C++11 has removing some old features. 
I propose Gambit should replace some of these old features.
